name = "orbit"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = false

durable_objects.bindings = [
  { name = "ORBIT_DO", class_name = "OrbitRelay" },
  { name = "PASSKEY_CHALLENGE_DO", class_name = "PasskeyChallengeStore" }
]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "zane"
database_id = "18a74ed9-eb94-4994-99f3-b4ebe5162046"

[[migrations]]
tag = "v1"
new_classes = ["OrbitRelay"]

[[migrations]]
tag = "v2"
new_classes = ["PasskeyChallengeStore"]
